from .mainWindow import MainWindow
from .newTitleDialog import NewTitleDialog
from .newUpdateDialog import NewUpdateDialog
from .devDialog import DevDialog
from .platformDialog import PlatformDialog
from .msgDialog import MsgDialog
from .editTitleWindow import EditTitleDialog
from .editUpdateWindow import EditUpdateDialog
from .aboutDialog import AboutDialog