# Form implementation generated from reading ui file 'ui/about.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import app


class Ui_DialogAbout(object):
    def setupUi(self, DialogAbout):
        DialogAbout.setObjectName("DialogAbout")
        DialogAbout.resize(330, 180)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogAbout.sizePolicy().hasHeightForWidth())
        DialogAbout.setSizePolicy(sizePolicy)
        DialogAbout.setMinimumSize(QtCore.QSize(330, 180))
        DialogAbout.setMaximumSize(QtCore.QSize(330, 180))
        font = QtGui.QFont()
        font.setPointSize(10)
        DialogAbout.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(app.resource_path("ui\\assets\\icon.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        DialogAbout.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(parent=DialogAbout)
        self.label.setGeometry(QtCore.QRect(20, 20, 64, 64))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(app.resource_path("ui\\assets\\database.png")))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=DialogAbout)
        self.label_2.setGeometry(QtCore.QRect(100, 20, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.labelPyQtVersion = QtWidgets.QLabel(parent=DialogAbout)
        self.labelPyQtVersion.setGeometry(QtCore.QRect(120, 90, 180, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.labelPyQtVersion.setFont(font)
        self.labelPyQtVersion.setObjectName("labelPyQtVersion")
        self.labelPyVersion = QtWidgets.QLabel(parent=DialogAbout)
        self.labelPyVersion.setGeometry(QtCore.QRect(120, 70, 180, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.labelPyVersion.setFont(font)
        self.labelPyVersion.setObjectName("labelPyVersion")
        self.labelVersion = QtWidgets.QLabel(parent=DialogAbout)
        self.labelVersion.setGeometry(QtCore.QRect(120, 50, 180, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.labelVersion.setFont(font)
        self.labelVersion.setObjectName("labelVersion")
        self.labelGithub = QtWidgets.QLabel(parent=DialogAbout)
        self.labelGithub.setGeometry(QtCore.QRect(120, 110, 180, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.labelGithub.setFont(font)
        self.labelGithub.setObjectName("labelGithub")
        self.labelCopyright = QtWidgets.QLabel(parent=DialogAbout)
        self.labelCopyright.setGeometry(QtCore.QRect(110, 140, 180, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.labelCopyright.setFont(font)
        self.labelCopyright.setObjectName("labelCopyright")

        self.retranslateUi(DialogAbout)
        QtCore.QMetaObject.connectSlotsByName(DialogAbout)

    def retranslateUi(self, DialogAbout):
        _translate = QtCore.QCoreApplication.translate
        DialogAbout.setWindowTitle(_translate("DialogAbout", "About"))
        self.label_2.setText(_translate("DialogAbout", "Python Database Manager"))
        self.labelPyQtVersion.setText(_translate("DialogAbout", "PyQt Version"))
        self.labelPyVersion.setText(_translate("DialogAbout", "Python Version"))
        self.labelVersion.setText(_translate("DialogAbout", "Version"))
        self.labelGithub.setText(_translate("DialogAbout", "Github Link"))
        self.labelCopyright.setText(_translate("DialogAbout", "Copyright 2025 amdilan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogAbout = QtWidgets.QDialog()
    ui = Ui_DialogAbout()
    ui.setupUi(DialogAbout)
    DialogAbout.show()
    sys.exit(app.exec())
