# Form implementation generated from reading ui file 'ui/platforms_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import app


class Ui_PlatformDialog(object):
    def setupUi(self, PlatformDialog):
        PlatformDialog.setObjectName("PlatformDialog")
        PlatformDialog.resize(390, 290)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlatformDialog.sizePolicy().hasHeightForWidth())
        PlatformDialog.setSizePolicy(sizePolicy)
        PlatformDialog.setMinimumSize(QtCore.QSize(390, 290))
        PlatformDialog.setMaximumSize(QtCore.QSize(390, 290))
        font = QtGui.QFont()
        font.setPointSize(10)
        PlatformDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(app.resource_path("ui\\assets\\drawer.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        PlatformDialog.setWindowIcon(icon)
        self.listWidgetPlat = QtWidgets.QListWidget(parent=PlatformDialog)
        self.listWidgetPlat.setGeometry(QtCore.QRect(20, 30, 271, 151))
        self.listWidgetPlat.setObjectName("listWidgetPlat")
        self.lineEditPlat = QtWidgets.QLineEdit(parent=PlatformDialog)
        self.lineEditPlat.setGeometry(QtCore.QRect(20, 210, 271, 21))
        self.lineEditPlat.setObjectName("lineEditPlat")
        self.pushButtonEdit = QtWidgets.QPushButton(parent=PlatformDialog)
        self.pushButtonEdit.setGeometry(QtCore.QRect(300, 60, 75, 24))
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.pushButtonDelete = QtWidgets.QPushButton(parent=PlatformDialog)
        self.pushButtonDelete.setGeometry(QtCore.QRect(300, 90, 75, 24))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.pushButtonSave = QtWidgets.QPushButton(parent=PlatformDialog)
        self.pushButtonSave.setGeometry(QtCore.QRect(300, 210, 75, 24))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonClose = QtWidgets.QPushButton(parent=PlatformDialog)
        self.pushButtonClose.setGeometry(QtCore.QRect(300, 250, 75, 24))
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.label = QtWidgets.QLabel(parent=PlatformDialog)
        self.label.setGeometry(QtCore.QRect(20, 250, 271, 21))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=PlatformDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 150, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=PlatformDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 150, 20))
        self.label_3.setObjectName("label_3")
        self.pushButtonNew = QtWidgets.QPushButton(parent=PlatformDialog)
        self.pushButtonNew.setGeometry(QtCore.QRect(300, 30, 75, 24))
        self.pushButtonNew.setObjectName("pushButtonNew")

        self.retranslateUi(PlatformDialog)
        self.pushButtonClose.clicked.connect(PlatformDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PlatformDialog)
        PlatformDialog.setTabOrder(self.pushButtonNew, self.lineEditPlat)
        PlatformDialog.setTabOrder(self.lineEditPlat, self.pushButtonSave)
        PlatformDialog.setTabOrder(self.pushButtonSave, self.listWidgetPlat)
        PlatformDialog.setTabOrder(self.listWidgetPlat, self.pushButtonEdit)
        PlatformDialog.setTabOrder(self.pushButtonEdit, self.pushButtonDelete)
        PlatformDialog.setTabOrder(self.pushButtonDelete, self.pushButtonClose)

    def retranslateUi(self, PlatformDialog):
        _translate = QtCore.QCoreApplication.translate
        PlatformDialog.setWindowTitle(_translate("PlatformDialog", "Manage Platforms"))
        self.pushButtonEdit.setText(_translate("PlatformDialog", "Edit"))
        self.pushButtonDelete.setText(_translate("PlatformDialog", "Delete"))
        self.pushButtonSave.setText(_translate("PlatformDialog", "Save"))
        self.pushButtonClose.setText(_translate("PlatformDialog", "Close"))
        self.label_2.setText(_translate("PlatformDialog", "Platforms :"))
        self.label_3.setText(_translate("PlatformDialog", "Platform Name :"))
        self.pushButtonNew.setText(_translate("PlatformDialog", "New"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlatformDialog = QtWidgets.QDialog()
    ui = Ui_PlatformDialog()
    ui.setupUi(PlatformDialog)
    PlatformDialog.show()
    sys.exit(app.exec())
